# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: monitis-SDK 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "monitis-SDK"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Ankur"]
  s.date = "2014-04-24"
  s.description = "TODO: longer description of your gem"
  s.email = "ankur.jain24@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "example/example.rb",
    "lib/monitis-SDK.rb",
    "lib/monitis-SDK/base.rb",
    "lib/monitis-SDK/contact.rb",
    "lib/monitis-SDK/monitis_error.rb",
    "lib/monitis-SDK/monitors/agents.rb",
    "lib/monitis-SDK/monitors/cloud_instances.rb",
    "lib/monitis-SDK/monitors/cpu_monitors.rb",
    "lib/monitis-SDK/monitors/custom_monitors.rb",
    "lib/monitis-SDK/monitors/drive_monitors.rb",
    "lib/monitis-SDK/monitors/external_monitors.rb",
    "lib/monitis-SDK/monitors/full_page_load_monitors.rb",
    "lib/monitis-SDK/monitors/http_monitors.rb",
    "lib/monitis-SDK/monitors/internal_monitors.rb",
    "lib/monitis-SDK/monitors/load_average_monitors.rb",
    "lib/monitis-SDK/monitors/memory_monitors.rb",
    "lib/monitis-SDK/monitors/ping_monitors.rb",
    "lib/monitis-SDK/monitors/process_monitors.rb",
    "lib/monitis-SDK/monitors/transaction_monitors.rb",
    "lib/monitis-SDK/monitors/visitor_trackers.rb",
    "lib/monitis-SDK/user.rb",
    "test/helper.rb",
    "test/sandbox_test.rb",
    "test/test_monitis-SDK.rb"
  ]
  s.homepage = "http://github.com/anjain/monitis-SDK"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.1"
  s.summary = "Ruby interface to the Monitis, all-in-one IT monitoring platform (http://www.monitis.com)"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<crack>, [">= 0"])
      s.add_development_dependency(%q<httparty>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<crack>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<crack>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0"])
  end
end

